//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruyenTranh.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int MaChiTIetPhieuNhap { get; set; }
        public int MaPhieuNhap { get; set; }
        public Nullable<int> MaTruyenTranh { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> Gia { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual TRUYENTRANH TRUYENTRANH { get; set; }
    }
}
